const TEAMS = [
  { id:'ck', name:'Chennai Kings',      shortName:'CK', city:'Chennai',   tagline:'The Golden Kingdom',      emoji:'👑', logo:'./assets/logos/chennai_kings.png', primary:'#F59E0B', secondary:'#1E1B4B', text:'#000', glow:'rgba(245,158,11,.5)',  gradient:'linear-gradient(135deg,#F59E0B,#B45309)' },
  { id:'bs', name:'Bengaluru Strikers', shortName:'BS', city:'Bengaluru', tagline:'Strike Fear, Code Bold',  emoji:'⚡', logo:'./assets/logos/bengaluru_strikers.png', primary:'#DC143C', secondary:'#1A1A1A', text:'#FFF', glow:'rgba(220,20,60,.5)',   gradient:'linear-gradient(135deg,#DC143C,#7C0A2A)' },
  { id:'mm', name:'Mumbai Mariners',    shortName:'MM', city:'Mumbai',    tagline:'Sail Through Code',       emoji:'⚓', logo:'./assets/logos/mumbai_mariners.png', primary:'#1D4ED8', secondary:'#0EA5E9', text:'#FFF', glow:'rgba(29,78,216,.5)',   gradient:'linear-gradient(135deg,#1D4ED8,#0EA5E9)' },
  { id:'kw', name:'Kolkata Warriors',   shortName:'KW', city:'Kolkata',   tagline:'Warriors of the East',   emoji:'⚔️', logo:'./assets/logos/kolkata_warriors.png', primary:'#7C3AED', secondary:'#F59E0B', text:'#FFF', glow:'rgba(124,58,237,.5)',  gradient:'linear-gradient(135deg,#7C3AED,#4C1D95)' },
  { id:'pl', name:'Punjab Lions',       shortName:'PL', city:'Punjab',    tagline:'Roar Through Algorithms', emoji:'🦁', logo:'./assets/logos/punjab_lions.png', primary:'#E11D48', secondary:'#94A3B8', text:'#FFF', glow:'rgba(225,29,72,.5)',   gradient:'linear-gradient(135deg,#E11D48,#9F1239)' },
  { id:'rr', name:'Rajasthan Rovers',   shortName:'RR', city:'Rajasthan', tagline:'Roving the Desert',      emoji:'🌵', logo:'./assets/logos/rajasthan_rovers.png', primary:'#DB2777', secondary:'#1D4ED8', text:'#FFF', glow:'rgba(219,39,119,.5)',  gradient:'linear-gradient(135deg,#DB2777,#831843)' },
  { id:'dd', name:'Delhi Defenders',    shortName:'DD', city:'Delhi',     tagline:'Defend the Throne',      emoji:'🛡️', logo:'./assets/logos/delhi_defenders.png', primary:'#1E40AF', secondary:'#DC2626', text:'#FFF', glow:'rgba(30,64,175,.5)',   gradient:'linear-gradient(135deg,#1E40AF,#1E3A8A)' },
  { id:'hb', name:'Hyderabad Blazers',  shortName:'HB', city:'Hyderabad', tagline:'Blazing Through Data',   emoji:'🔥', logo:'./assets/logos/hyderabad_blazers.png', primary:'#EA580C', secondary:'#1A1A1A', text:'#FFF', glow:'rgba(234,88,12,.5)',   gradient:'linear-gradient(135deg,#EA580C,#9A3412)' },
];
